import type * as activities from './activities';
import { proxyActivities } from '@temporalio/workflow';

/**
 * Workflow: TestSimpleWorkflow
 * Simple test workflow with one activity
 * Generated by Pattern-Based Compiler v1.0
 */

/** Simple test workflow with one activity */
export async function TestSimpleWorkflow(input: any): Promise<any> {
  // Activity proxies (timeout: 30s)
const activities30s = proxyActivities<typeof activities>({
  startToCloseTimeout: '30s',
  retry: {
    initialInterval: '1s',
    backoffCoefficient: 2,
    maximumAttempts: 3,
  }
});

  // Execute activity: Say Hello
  const result_activity_hello = await activities30s.sayHello(input);

  return result_activity_hello;
}
