'use client';

import { Card, YStack, XStack, Text, Button } from 'tamagui';
import { Badge } from '../shared/Badge';
import { Search, Trash2, Edit } from 'lucide-react';
import { api as trpc } from '@/lib/trpc/client';

interface QueryCardProps {
  query: {
    id: string;
    workflow_id: string;
    query_name: string;
    description?: string;
    return_type_schema?: Record<string, any>;
    auto_generated: boolean;
  };
  onUpdate?: () => void;
}

export function QueryCard({ query, onUpdate }: QueryCardProps) {
  const utils = trpc.useContext();
  
  const deleteMutation = trpc.queries.delete.useMutation({
    onSuccess: () => {
      utils.queries.list.invalidate();
      onUpdate?.();
    },
  });

  const handleDelete = async () => {
    if (query.auto_generated) {
      alert('Cannot delete auto-generated query handlers. Delete the associated work queue instead.');
      return;
    }

    if (confirm(`Delete query "${query.query_name}"? This cannot be undone.`)) {
      await deleteMutation.mutateAsync({ 
        id: query.id,
        workflowId: query.workflow_id 
      });
    }
  };

  return (
    <Card p="$4" borderWidth={1} borderColor="$borderColor" >
      <YStack gap="$3">
        {/* Header */}
        <XStack ai="center" jc="space-between">
          <XStack ai="center" gap="$3">
            <Search size={24} color="$teal9" />
            <YStack gap="$1">
              <XStack ai="center" gap="$2">
                <Text fontSize="$5" fontWeight="600">
                  {query.query_name}
                </Text>
                {query.auto_generated && (
                  <Badge size="$1" bg="$blue5">AUTO</Badge>
                )}
              </XStack>
              {query.description && (
                <Text fontSize="$3" color="$gray11">
                  {query.description}
                </Text>
              )}
            </YStack>
          </XStack>

          <XStack gap="$2">
            {!query.auto_generated && (
              <>
                <Button size="$2" icon={Edit} chromeless>
                  Edit
                </Button>
                <Button
                  size="$2"
                  icon={Trash2}
                  onPress={handleDelete}
                  disabled={deleteMutation.isLoading}
                  chromeless
                  color="$red10"
                >
                  Delete
                </Button>
              </>
            )}
          </XStack>
        </XStack>

        {/* Return Type Schema */}
        {query.return_type_schema && (
          <Card bg="$gray2" p="$3" borderWidth={1} borderColor="$gray6">
            <YStack gap="$2">
              <Text fontSize="$3" fontWeight="600" color="$gray12">
                Return Type
              </Text>
              <Text fontSize="$1" fontFamily="$mono" color="$gray11">
                {JSON.stringify(query.return_type_schema, null, 2)}
              </Text>
            </YStack>
          </Card>
        )}

        {query.auto_generated && (
          <Text fontSize="$2" color="$teal11" fontStyle="italic">
            This query was auto-generated by a work queue. It will be deleted if the work queue is removed.
          </Text>
        )}
      </YStack>
    </Card>
  );
}

