'use client';

import { Card, YStack, XStack, Text, Button } from 'tamagui';
import { Badge } from '../shared/Badge';
import { Send, Trash2, Edit } from 'lucide-react';
import { api as trpc } from '@/lib/trpc/client';

interface SignalCardProps {
  signal: {
    id: string;
    workflow_id: string;
    signal_name: string;
    description?: string;
    parameters_schema?: Record<string, any>;
    auto_generated: boolean;
  };
  onUpdate?: () => void;
}

export function SignalCard({ signal, onUpdate }: SignalCardProps) {
  const utils = trpc.useContext();
  
  const deleteMutation = trpc.signals.delete.useMutation({
    onSuccess: () => {
      utils.signals.list.invalidate();
      onUpdate?.();
    },
  });

  const handleDelete = async () => {
    if (signal.auto_generated) {
      alert('Cannot delete auto-generated signal handlers. Delete the associated work queue instead.');
      return;
    }

    if (confirm(`Delete signal "${signal.signal_name}"? This cannot be undone.`)) {
      await deleteMutation.mutateAsync({ 
        id: signal.id,
        workflowId: signal.workflow_id 
      });
    }
  };

  return (
    <Card p="$4" borderWidth={1} borderColor="$borderColor" >
      <YStack gap="$3">
        {/* Header */}
        <XStack ai="center" jc="space-between">
          <XStack ai="center" gap="$3">
            <Send size={24} color="$orange9" />
            <YStack gap="$1">
              <XStack ai="center" gap="$2">
                <Text fontSize="$5" fontWeight="600">
                  {signal.signal_name}
                </Text>
                {signal.auto_generated && (
                  <Badge size="$1" bg="$blue5">AUTO</Badge>
                )}
              </XStack>
              {signal.description && (
                <Text fontSize="$3" color="$gray11">
                  {signal.description}
                </Text>
              )}
            </YStack>
          </XStack>

          <XStack gap="$2">
            {!signal.auto_generated && (
              <>
                <Button size="$2" icon={Edit} chromeless>
                  Edit
                </Button>
                <Button
                  size="$2"
                  icon={Trash2}
                  onPress={handleDelete}
                  disabled={deleteMutation.isLoading}
                  chromeless
                  color="$red10"
                >
                  Delete
                </Button>
              </>
            )}
          </XStack>
        </XStack>

        {/* Parameters Schema */}
        {signal.parameters_schema && (
          <Card bg="$gray2" p="$3" borderWidth={1} borderColor="$gray6">
            <YStack gap="$2">
              <Text fontSize="$3" fontWeight="600" color="$gray12">
                Parameters
              </Text>
              <Text fontSize="$1" fontFamily="$mono" color="$gray11">
                {JSON.stringify(signal.parameters_schema, null, 2)}
              </Text>
            </YStack>
          </Card>
        )}

        {signal.auto_generated && (
          <Text fontSize="$2" color="$blue11" fontStyle="italic">
            This signal was auto-generated by a work queue. It will be deleted if the work queue is removed.
          </Text>
        )}
      </YStack>
    </Card>
  );
}

